### ISSUE TITLE
Move to Discordie

### ISSUE THREAD

**Issue by Guichaguri** [Guichaguri/DiscordDJ#5]
Right now DiscordDJ is using discord.js, there is two main reasons why moving to Discordie:
* Internal voice encoding (not just `node-opus`, less trouble in the installation)
* Multiple voice connections (a must for DiscordDJ)

Using discord.js, you can **only** use DiscordDJ with another bot discord.js
Using Discordie, you can use DiscordDJ with Discordie, discord.js and discord.io

**Task List**
- [x] Figure out how to use Discordie
- [x] Figure out how Discordie audio encoding works
- [x] Prepare basic login (with email and password OR token)
- [x] Prepare multiple voice connections
- [x] Prepare basic audio encoding
- [x] Port chat handler
- [x] Port commands
- [x] Port runtime
- [x] Port the rest of the discord.js calls

I'm recoding most of the code to work with Discordie, and I'm also planning for the future to support other libraries (and even the official API) to reduce memory/cpu usage when using the API

**Comment by Guichaguri** [comment]
Done.
